-- Update Privacy and Terms; add Disclaimer page and footer link

INSERT INTO public.content (page, section, key, value, type, "order") VALUES
('privacy', 'sections', 'how-we-use-information', '{"id":"how-we-use-information","title":"How we use information","paragraphs":["We use the information above to:"],"list":["Send book release updates and occasional reflections or announcements you signed up for.","Operate, secure, and improve the website.","Respond to questions or requests you send us.","Understand general site usage through analytics and similar tools so we can maintain performance, fix problems, and improve the experience."]}'::jsonb, 'list_item', 1),
('privacy', 'sections', 'cookies', '{"id":"cookies","title":"Cookies and similar technologies","paragraphs":["We use cookies and similar technologies to help the site function properly, remember certain preferences, and understand how visitors use the site.","We may use analytics tools that collect aggregated usage data, such as pages visited, referring pages, and general navigation patterns, to help us improve the site. We do not use analytics to sell your personal information.","You can control cookies through your browser settings. Disabling cookies may affect some site features."]}'::jsonb, 'list_item', 2),
('privacy', 'sections', 'how-we-share', '{"id":"how-we-share","title":"How we share information","paragraphs":["We do not sell your personal information. We share information only with trusted third-party service providers that help us run the site, such as providers used for website hosting, analytics, email communications, and data storage. These providers process data on our behalf under their own privacy terms and only as needed to perform their work.","We may also disclose information if required by law, to protect rights and safety, or in connection with a business transfer, such as a merger or acquisition."]}'::jsonb, 'list_item', 3),
('privacy', 'sections', 'email-choices', '{"id":"email-choices","title":"Email communications and your choices","paragraphs":["If you join a mailing list, we will use your email for the purpose described at signup. You can unsubscribe from marketing or update emails at any time by using the unsubscribe link in an email, if provided, or by contacting us directly.","Even if you unsubscribe from updates, we may still keep a record that you previously signed up so we do not re-add you by mistake."]}'::jsonb, 'list_item', 4),
('privacy', 'sections', 'retention', '{"id":"retention","title":"How long we keep information","paragraphs":["We keep signup information for as long as needed to send the communications you requested, maintain our records, and comply with legal obligations. When information is no longer needed, we delete it or anonymize it where practical."]}'::jsonb, 'list_item', 5),
('privacy', 'sections', 'security', '{"id":"security","title":"Security","paragraphs":["We use reasonable administrative, technical, and organizational measures to protect information. No website or email system can be guaranteed completely secure, so please use caution when sharing information online."]}'::jsonb, 'list_item', 6),
('privacy', 'sections', 'your-rights', '{"id":"your-rights","title":"Your rights and requests","paragraphs":["Depending on where you live, you may have rights to access, correct, delete, or restrict certain uses of your personal information, or to object to processing. To make a request, email us using the contact details below. We may need to verify your request before responding."]}'::jsonb, 'list_item', 7),
('privacy', 'sections', 'children', '{"id":"children","title":"Children''s privacy","paragraphs":["This site is intended for adults. We do not knowingly collect personal information from children under 13. If you believe a child has provided us information, contact us and we will take steps to delete it."]}'::jsonb, 'list_item', 8),
('privacy', 'sections', 'international', '{"id":"international","title":"International visitors","paragraphs":["If you visit from outside the United States, your information may be processed in the United States or in other countries where our service providers operate. By using the site, you understand that your information may be transferred to locations with different data protection laws than your own."]}'::jsonb, 'list_item', 9),
('privacy', 'sections', 'changes', '{"id":"changes","title":"Changes to this policy","paragraphs":["We may update this Privacy Policy from time to time. When we do, we will revise the effective date at the top of this page. Continued use of the site after changes become effective means you accept the updated policy."]}'::jsonb, 'list_item', 10),
('privacy', 'sections', 'contact', '{"id":"contact","title":"Contact us","paragraphs":["Questions about this policy or your information can be sent to hello@eyesclosed.love."]}'::jsonb, 'list_item', 11),

('terms', 'sections', 'not-advice', '{"id":"not-advice","title":"Educational content only","paragraphs":["Content on this site is informational, educational, and offered for personal reflection only. It reflects perspectives on awareness, presence, and inner inquiry and is not intended to provide medical, psychological, psychiatric, therapeutic, legal, financial, or other professional advice, nor is it intended to diagnose, treat, cure, or prevent any medical or mental health condition.","Nothing on this site creates a therapist-client, doctor-patient, coaching, or other professional relationship between you and Eyes Closed or Sonika Cottman. If you need professional support, consult a qualified licensed provider in your area.","You are responsible for your own choices, decisions, and well-being. Please also read our Disclaimer for additional information about the limits of site content."]}'::jsonb, 'list_item', 1),
('terms', 'sections', 'no-guarantees', '{"id":"no-guarantees","title":"No guarantees","paragraphs":["Individual experiences will vary. We make no guarantees regarding personal, emotional, spiritual, financial, or other outcomes from using this website or its content."]}'::jsonb, 'list_item', 2),
('terms', 'sections', 'acceptable-use', '{"id":"acceptable-use","title":"Acceptable use","paragraphs":["You agree not to:"],"list":["Use the site in any way that violates law or the rights of others.","Attempt to gain unauthorized access to the site, its systems, or related accounts.","Scrape, copy, or redistribute site content at scale without permission.","Upload malware, spam, or harmful code.","Harass, impersonate, or misrepresent your affiliation with Eyes Closed or Sonika Cottman."]}'::jsonb, 'list_item', 3),
('terms', 'sections', 'intellectual-property', '{"id":"intellectual-property","title":"Intellectual property","paragraphs":["The site design, text, images, logos, graphics, audio, video, and other materials are owned by Eyes Closed, Sonika Cottman, or licensors and are protected by copyright and other intellectual property laws.","You may view and download content for personal, non-commercial use only. You may not reproduce, distribute, modify, publicly display, or create derivative works from site content without prior written permission, except where allowed by law.","Nothing in these Terms grants you any ownership rights in the website or its content."]}'::jsonb, 'list_item', 4),
('terms', 'sections', 'email-lists', '{"id":"email-lists","title":"Email lists and communications","paragraphs":["When you submit your email address, you confirm that the address is yours and that you agree to receive the communications described at signup.","You can unsubscribe from optional updates as described in our Privacy Policy. We may still send essential service-related messages when necessary."]}'::jsonb, 'list_item', 5),
('terms', 'sections', 'third-party-links', '{"id":"third-party-links","title":"Third-party links and services","paragraphs":["The site may link to third-party websites or services. We do not control and are not responsible for their content, policies, or practices. Your use of third-party services is at your own risk."]}'::jsonb, 'list_item', 6),
('terms', 'sections', 'disclaimer', '{"id":"disclaimer","title":"Disclaimer of warranties","paragraphs":["The site and all content are provided \"as is\" and \"as available,\" without warranties of any kind, whether express or implied, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement.","We do not warrant that the site will be uninterrupted, error-free, secure, or free of harmful components."]}'::jsonb, 'list_item', 7),
('terms', 'sections', 'liability', '{"id":"liability","title":"Limitation of liability","paragraphs":["To the fullest extent permitted by law, Eyes Closed, Sonika Cottman, and related parties will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profits, data, goodwill, or other intangible losses, arising from or related to your use of the site or reliance on its content.","Our total liability for any claim arising out of these Terms or the site will not exceed the greater of one hundred U.S. dollars (USD $100) or the amount you paid us, if any, in the twelve months before the claim."]}'::jsonb, 'list_item', 8),
('terms', 'sections', 'indemnity', '{"id":"indemnity","title":"Indemnification","paragraphs":["You agree to defend, indemnify, and hold harmless Eyes Closed and Sonika Cottman from claims, damages, losses, and expenses (including reasonable legal fees) arising from your misuse of the site or violation of these Terms."]}'::jsonb, 'list_item', 9),
('terms', 'sections', 'changes', '{"id":"changes","title":"Changes to these Terms","paragraphs":["We may update these Terms from time to time. The effective date at the top of this page will show when they were last revised. Continued use of the site after changes become effective means you accept the updated Terms."]}'::jsonb, 'list_item', 10),
('terms', 'sections', 'governing-law', '{"id":"governing-law","title":"Governing law","paragraphs":["These Terms are governed by the laws of the State of Nevada, United States, without regard to conflict-of-law rules. Any dispute arising from these Terms or the site will be brought in the state or federal courts located in Nevada, unless applicable law requires otherwise."]}'::jsonb, 'list_item', 11),
('terms', 'sections', 'contact', '{"id":"contact","title":"Contact","paragraphs":["Questions about these Terms can be sent to hello@eyesclosed.love."]}'::jsonb, 'list_item', 12),

('disclaimer', 'header', 'title', '{"text":"Disclaimer"}', 'text', 0),
('disclaimer', 'header', 'effective_date', '{"text":"June 29, 2026"}', 'text', 0),
('disclaimer', 'header', 'intro', '{"text":"The following disclaimer applies to all content and materials on the Eyes Closed website, including articles, videos, audio recordings, guided practices, downloadable resources, newsletters, courses, and other offerings."}', 'text', 0),
('disclaimer', 'header', 'contact_email', '{"text":"hello@eyesclosed.love"}', 'text', 0),
('disclaimer', 'sections', 'purpose', '{"id":"purpose","title":"Purpose of our content","paragraphs":["The content provided on the Eyes Closed website is intended for informational, educational, inspirational, and personal reflection purposes only.","The information shared through Eyes Closed reflects the personal experiences, perspectives, and interpretations of Sonika Cottman and is offered to encourage greater awareness, presence, and self-inquiry."]}'::jsonb, 'list_item', 0),
('disclaimer', 'sections', 'not-professional-advice', '{"id":"not-professional-advice","title":"Not professional advice","paragraphs":["Content on this website is not intended to provide medical, psychological, psychiatric, therapeutic, legal, financial, or other professional advice, nor is it intended to diagnose, treat, cure, or prevent any medical or mental health condition."]}'::jsonb, 'list_item', 1),
('disclaimer', 'sections', 'no-relationship', '{"id":"no-relationship","title":"No professional relationship","paragraphs":["Nothing on this website creates a therapist-client, doctor-patient, coaching, or other professional relationship between you and Eyes Closed or Sonika Cottman."]}'::jsonb, 'list_item', 2),
('disclaimer', 'sections', 'your-responsibility', '{"id":"your-responsibility","title":"Your responsibility","paragraphs":["You are responsible for your own decisions, actions, and well-being. If you have concerns regarding your physical or mental health, or any other matter requiring professional guidance, please seek advice from an appropriately qualified and licensed professional."]}'::jsonb, 'list_item', 3),
('disclaimer', 'sections', 'no-guarantees', '{"id":"no-guarantees","title":"No guarantees","paragraphs":["While we strive to provide thoughtful and accurate information, we make no representations or warranties regarding the completeness, accuracy, reliability, or suitability of any content on this website.","Individual experiences may vary, and we make no guarantees regarding personal, emotional, spiritual, financial, or other outcomes resulting from the use of this website or its content."]}'::jsonb, 'list_item', 4),
('disclaimer', 'sections', 'use-at-your-own-risk', '{"id":"use-at-your-own-risk","title":"Use at your own risk","paragraphs":["By using this website, you acknowledge that you do so voluntarily and at your own risk. To the fullest extent permitted by law, Eyes Closed and Sonika Cottman disclaim any liability for any loss, injury, or damages arising directly or indirectly from the use of, or reliance on, the information provided on this website."]}'::jsonb, 'list_item', 5),

('footer', 'legal', 'disclaimer', '{"text": "Disclaimer", "href": "/disclaimer"}', 'link', 2)
ON CONFLICT (page, section, key) DO UPDATE SET
  value = EXCLUDED.value,
  type = EXCLUDED.type,
  "order" = EXCLUDED."order",
  updated_at = now();
